#ifndef THPRAC98_SRC_MYSTDLIB_ERRNO_HPP_
#define THPRAC98_SRC_MYSTDLIB_ERRNO_HPP_

#define errno errno_
extern int errno_;

// DOS 2.0+ extended error codes
#define E_DOS_FUNCTION_NUMBER_INVALID 0x01
#define E_DOS_FILE_NOT_FOUND 0x02
#define E_DOS_PATH_NOT_FOUND 0x03
#define E_DOS_TOO_MANY_OPEN_FILES 0x04
#define E_DOS_ACCESS_DENIED 0x05
#define E_DOS_INVALID_HANDLE 0x06
#define E_DOS_MEMORY_CONTROL_BLOCK_DESTORYED 0x07
#define E_DOS_INSUFFICIENT_MEMORY 0x08
#define E_DOS_MEMORY_BLOCK_ADDRESS_INVALID 0x09
#define E_DOS_ENVIRONMENT_INVALID 0x0A
#define E_DOS_FORMAT_INVALID 0x0B
#define E_DOS_ACCESS_CODE_INVALID 0x0C
#define E_DOS_DATA_INVALID 0x0D
#define E_DOS_INVALID_DRIVE 0x0F
#define E_DOS_ATTEMPTED_TO_REMOVE_CURRENT_DIRECTORY 0x10
#define E_DOS_NOT_SAME_DEVICE 0x11
#define E_DOS_NO_MORE_FILES 0x12

// DOS 3.0+ extended error codes
#define E_DOS_DISK_WRITE_PROTECTED 0x13
#define E_DOS_UNKNOWN_UNIT 0x14
#define E_DOS_DRIVE_NOT_READY 0x15
#define E_DOS_UNKNOWN_COMMAND 0x16
#define E_DOS_DATA_ERROR 0x17
#define E_DOS_BAD_REQUEST_STRUCTURE_LENGTH 0x18
#define E_DOS_SEEK_ERROR 0x19
#define E_DOS_UNKNOWN_MEDIA_TYPE 0x1A
#define E_DOS_SECTOR_NOT_FOUND 0x1B
#define E_DOS_PRINTER_OUT_OF_PAPER 0x1C
#define E_DOS_WRITE_FAULT 0x1D
#define E_DOS_READ_FAULT 0x1E
#define E_DOS_GENERAL_FAILURE 0x1F
#define E_DOS_SHARING_VIOLATION 0x20
#define E_DOS_LOCK_VIOLATION 0x21
#define E_DOS_DISK_CHANGE_INVALID 0x22
#define E_DOS_FCB_UNAVAILABLE 0x23
#define E_DOS_SHARING_BUFFER_OVERFLOW 0x24

// My own error codes
#define E_FILE_HANDLER_POOL_FULL 0x101
#define E_INVALID_ARGUMENT 0x102

#endif  // #ifndef THPRAC98_SRC_MYSTDLIB_ERRNO_HPP_