  KEY_NULL = 0,  // not a real key, for configuration use

  // character typed:          none | +shift | +kana | +shift+kana

  KEY_1_NU,   //                1        !      ヌ                            .
  KEY_2_FU,   //                2        "      フ                            .
  KEY_3_A,    //                3        #      ア       ァ                   .
  KEY_4_U,    //                4        $      ウ       ゥ                   .
  KEY_5_E,    //                5        %      エ       ェ                   .
  KEY_6_O,    //                6        &      オ       ォ                   .
  KEY_7_YA,   //                7        '      ヤ       ャ                   .
  KEY_8_YU,   //                8        (      ユ       ュ                   .
  KEY_9_YO,   //                9        )      ヨ       ョ                   .
  KEY_0_WA,   //                0               ワ       ヲ                   .

  KEY_A_CHI,  //                A               チ                            .
  KEY_B_KO,   //                B               コ                            .
  KEY_C_SO,   //                C               ソ                            .
  KEY_D_SHI,  //                D               シ                            .
  KEY_E_I,    //                E               イ                            .
  KEY_F_HA,   //                F               ハ                            .
  KEY_G_KI,   //                G               キ                            .
  KEY_H_KU,   //                H               ク                            .
  KEY_I_NI,   //                I               ニ                            .
  KEY_J_MA,   //                J               マ                            .
  KEY_K_NO,   //                K               ノ                            .
  KEY_L_RI,   //                L               リ                            .
  KEY_M_MO,   //                M               モ                            .
  KEY_N_MI,   //                N               ミ                            .
  KEY_O_RA,   //                O               ラ                            .
  KEY_P_SE,   //                P               セ                            .
  KEY_Q_TA,   //                Q               タ                            .
  KEY_R_SU,   //                R               ス                            .
  KEY_S_TO,   //                S               ト                            .
  KEY_T_KA,   //                T               カ                            .
  KEY_U_NA,   //                U               ナ                            .
  KEY_V_HI,   //                V               ヒ                            .
  KEY_W_TE,   //                W               テ                            .
  KEY_X_SA,   //                X               サ                            .
  KEY_Y_N,    //                Y               ン                            .
  KEY_Z_TSU,  //                Z               ツ       ッ                   .

  KEY_MINUS_HO,            //   -        =      ホ                            .
  KEY_CARET_HE,            //   ^               ヘ                            .
  KEY_YEN_CHOONPU,         //   ￥       |      ー(長音符)                     .
  KEY_AT_DAKUTEN,          //   @        ~      ゛(濁点)                      .
  KEY_LEFT_BRACKET_KUTEN,  //   [        {      。(句点)   「(始め鉤括弧)       .
  KEY_SEMICOLON_RE,        //   ;        +      レ                            .
  KEY_COLON_KE,            //   :        *      ケ                            .
  KEY_RIGHT_BRACKET_MU,    //   ]        }      ム       」(終わり鉤括弧)       .
  KEY_COMMA_NE,            //   ,        <      ネ       、(読点)              .
  KEY_DOT_RU,              //   .        >      ル       ゜(半濁点)            .
  KEY_SLASH_NU,            //   /        ?      ヌ       ・(中黒)             .
  KEY_RO,                  //            _      ロ

  KEY_ESC,
  KEY_BS,  // BackSpace
  KEY_TAB,
  KEY_ENTER,
  KEY_SPACE,
  KEY_XFER,
  KEY_ROLL_UP,
  KEY_ROLL_DOWN,
  KEY_INS,
  KEY_DEL,
  KEY_UP,
  KEY_LEFT,
  KEY_RIGHT,
  KEY_DOWN,
  KEY_HOME_CLR,
  KEY_HELP,
  KEY_NFER,
  KEY_HOME,
  KEY_STOP,
  KEY_COPY,
  KEY_SHIFT,
  KEY_CAPS,
  KEY_KANA,  // 仮名                                                          .
  KEY_GRPH,
  KEY_CTRL,

  KEY_NUMPAD_PLUS,
  KEY_NUMPAD_MINUS,
  KEY_NUMPAD_MULTIPLY,
  KEY_NUMPAD_DIVIDE,
  KEY_NUMPAD_EQUAL,
  KEY_NUMPAD_COMMA,
  KEY_NUMPAD_DOT,
  KEY_NUMPAD_0,
  KEY_NUMPAD_1,
  KEY_NUMPAD_2,
  KEY_NUMPAD_3,
  KEY_NUMPAD_4,
  KEY_NUMPAD_5,
  KEY_NUMPAD_6,
  KEY_NUMPAD_7,
  KEY_NUMPAD_8,
  KEY_NUMPAD_9,

  KEY_F1,
  KEY_F2,
  KEY_F3,
  KEY_F4,
  KEY_F5,
  KEY_F6,
  KEY_F7,
  KEY_F8,
  KEY_F9,
  KEY_F10,
  KEY_VF1,
  KEY_VF2,
  KEY_VF3,
  KEY_VF4,
  KEY_VF5,
